UPDATE AplicacaoFitofarmaco SET FatorProducaoID = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Colheita SET ProdutoID = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Cultivo SET CulturaID = ?, ParcelaID = ?, DataInicio = ?, DataFim = ?, Quantidade = ?, UnidadeID = ? WHERE CultivoID = ?;
UPDATE Cultura SET Variedade = ?, EspecieVegetalID = ? WHERE CulturaID = ?;
UPDATE Edificio SET DesignacaoEdificio = ?, Area = ?, UnidadeID = ?, TipoEdificioID = ? WHERE EdificioID = ?;
UPDATE Elemento SET Nome = ? WHERE ElementoID = ?;
UPDATE EspecieVegetal SET DesignacaoEspecie = ?, NomeComum = ?, TipoCulturaID = ? WHERE EspecieVegetalID = ?;
UPDATE EstadoFenologico SET EpocaSementeiraPlantacao = ?, EpocaPoda = ?, EpocaFloracao = ?, EpocaColheita = ?, CulturaID = ?, ParcelaID = ?, CultivoCultivoID = ? WHERE EstadoFenologicoID = ?;
UPDATE Fabricante SET DesignacaoFabricante = ? WHERE FabricanteID = ?;
UPDATE FatorProducao_Elemento SET Quantidade = ?, UnidadeID = ? WHERE ElementoID = ? AND FatorProducaoID = ?;
UPDATE FatorProdução SET NomeComercial = ?, FabricanteID = ?, FormatoID = ?, TipoFatorProducaoID = ? WHERE FatorProducaoID = ?;
UPDATE Fertilizacao SET FatorProducaoID = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE FormaDispersao SET DesignacaoFormaDispersao = ? WHERE FormaDispersaoID = ?;
UPDATE Formato SET DescricaoFormato = ? WHERE FormatoID = ?;
UPDATE Grandeza SET DesignacaoGrandeza = ? WHERE GrandezaID = ?;
UPDATE IncorporacaoSolo SET CultivoID = ? WHERE OperacaoID = ?;
UPDATE Medição SET Timestamp = ?, ValorMedido = ?, UnidadeID = ?, SensorSoloID = ?, SensorMeteorologicoID = ? WHERE MedicaoID = ?;
UPDATE Monda SET Modo = ?, CultivoID = ?, FatorProducaoID = ? WHERE OperacaoID = ?;
UPDATE Operacao SET DataRealizacao = ?, Quantidade = ?, TipoOperacao = ?, UnidadeID = ? WHERE OperacaoID = ?;
UPDATE Parcela SET Designacao = ?, Area = ?, UnidadeID = ? WHERE ParcelaID = ?;
UPDATE Parcela_SensorSolo SET  WHERE ParcelaID = ? AND SensorSoloID = ?;
UPDATE PlanoAgricola SET Ano = ? WHERE PlanoAgricolaID = ?;
UPDATE PlanoColheita SET DataPrevista = ?, QuantidadePrevista = ?, PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoColheitaID = ?;
UPDATE PlanoCorrecaoMineral SET PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoCorrecaoMineralID = ?;
UPDATE PlanoFertilizacao SET DataPrevista = ?, ViaAplicacaoID = ?, PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoFertilizacaoID = ?;
UPDATE PlanoFertilizacao_FatorProdução SET  WHERE PlanoFertilizacaoID = ? AND FatorProducaoID = ?;
UPDATE PlanoRega SET QuantidadeRega = ?, Periodicidade = ?, PlanoAgricolaID = ?, SetorID = ? WHERE PlanoRegaID = ?;
UPDATE PlanoRega_FatorProdução SET  WHERE PlanoRegaID = ? AND FatorProducaoID = ?;
UPDATE Plantacao SET CultivoID = ? WHERE OperacaoID = ?;
UPDATE Poda SET CultivoID = ? WHERE OperacaoID = ?;
UPDATE Produto SET DesignacaoProduto = ?, CulturaID = ? WHERE ProdutoID = ?;
UPDATE Rega SET Hora = ?, Duracao = ?, SetorID = ? WHERE OperacaoID = ?;
UPDATE Sementeira SET CultivoID = ? WHERE OperacaoID = ?;
UPDATE SensorMeteorologico SET TipoSensorID = ? WHERE SensorMeteorologicoID = ?;
UPDATE SensorSolo SET TipoSensorID = ? WHERE SensorSoloID = ?;
UPDATE Setor SET Caudal = ?, DataInicio = ?, DataFim = ?, FormaDispersaoID = ? WHERE SetorID = ?;
UPDATE Setor_Parcela SET  WHERE SetorID = ? AND ParcelaID = ?;
UPDATE TipoCultura SET DesignacaoTipoCultura = ? WHERE TipoCulturaID = ?;
UPDATE TipoEdificio SET DesignacaoTipoEdificio = ? WHERE TipoEdificioID = ?;
UPDATE TipoFatorProducao SET DescricaoTipoFatorProducao = ? WHERE TipoFatorProducaoID = ?;
UPDATE TipoSensor SET TipoSensor = ?, GrandezaID = ? WHERE TipoSensorID = ?;
UPDATE Unidade SET DescricaoUnidade = ? WHERE UnidadeID = ?;
UPDATE ViaAplicacao SET DesignacaoViaAplicacao = ? WHERE ViaAplicacaoID = ?;
UPDATE ViaAplicacao_FatorProdução SET  WHERE ViaAplicacaoID = ? AND FatorProducaoID = ?;

