SELECT OperacaoID, FatorProducaoID, CultivoID FROM AplicacaoFitofarmaco;
SELECT OperacaoID, ProdutoID, CultivoID FROM Colheita;
SELECT CultivoID, CulturaID, ParcelaID, DataInicio, DataFim, Quantidade, UnidadeID FROM Cultivo;
SELECT CulturaID, Variedade, EspecieVegetalID FROM Cultura;
SELECT EdificioID, DesignacaoEdificio, Area, UnidadeID, TipoEdificioID FROM Edificio;
SELECT ElementoID, Nome FROM Elemento;
SELECT EspecieVegetalID, DesignacaoEspecie, NomeComum, TipoCulturaID FROM EspecieVegetal;
SELECT EstadoFenologicoID, EpocaSementeiraPlantacao, EpocaPoda, EpocaFloracao, EpocaColheita, CulturaID, ParcelaID, CultivoCultivoID FROM EstadoFenologico;
SELECT FabricanteID, DesignacaoFabricante FROM Fabricante;
SELECT ElementoID, FatorProducaoID, Quantidade, UnidadeID FROM FatorProducao_Elemento;
SELECT FatorProducaoID, NomeComercial, FabricanteID, FormatoID, TipoFatorProducaoID FROM FatorProdução;
SELECT OperacaoID, FatorProducaoID, CultivoID FROM Fertilizacao;
SELECT FormaDispersaoID, DesignacaoFormaDispersao FROM FormaDispersao;
SELECT FormatoID, DescricaoFormato FROM Formato;
SELECT GrandezaID, DesignacaoGrandeza FROM Grandeza;
SELECT OperacaoID, CultivoID FROM IncorporacaoSolo;
SELECT MedicaoID, Timestamp, ValorMedido, UnidadeID, SensorSoloID, SensorMeteorologicoID FROM Medição;
SELECT OperacaoID, Modo, CultivoID, FatorProducaoID FROM Monda;
SELECT OperacaoID, DataRealizacao, Quantidade, TipoOperacao, UnidadeID FROM Operacao;
SELECT ParcelaID, Designacao, Area, UnidadeID FROM Parcela;
SELECT ParcelaID, SensorSoloID FROM Parcela_SensorSolo;
SELECT PlanoAgricolaID, Ano FROM PlanoAgricola;
SELECT PlanoColheitaID, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CultivoID FROM PlanoColheita;
SELECT PlanoCorrecaoMineralID, PlanoAgricolaID, CultivoID FROM PlanoCorrecaoMineral;
SELECT PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CultivoID FROM PlanoFertilizacao;
SELECT PlanoFertilizacaoID, FatorProducaoID FROM PlanoFertilizacao_FatorProdução;
SELECT PlanoRegaID, QuantidadeRega, Periodicidade, PlanoAgricolaID, SetorID FROM PlanoRega;
SELECT PlanoRegaID, FatorProducaoID FROM PlanoRega_FatorProdução;
SELECT OperacaoID, CultivoID FROM Plantacao;
SELECT OperacaoID, CultivoID FROM Poda;
SELECT ProdutoID, DesignacaoProduto, CulturaID FROM Produto;
SELECT OperacaoID, Hora, Duracao, SetorID FROM Rega;
SELECT OperacaoID, CultivoID FROM Sementeira;
SELECT SensorMeteorologicoID, TipoSensorID FROM SensorMeteorologico;
SELECT SensorSoloID, TipoSensorID FROM SensorSolo;
SELECT SetorID, Caudal, DataInicio, DataFim, FormaDispersaoID FROM Setor;
SELECT SetorID, ParcelaID FROM Setor_Parcela;
SELECT TipoCulturaID, DesignacaoTipoCultura FROM TipoCultura;
SELECT TipoEdificioID, DesignacaoTipoEdificio FROM TipoEdificio;
SELECT TipoFatorProducaoID, DescricaoTipoFatorProducao FROM TipoFatorProducao;
SELECT TipoSensorID, TipoSensor, GrandezaID FROM TipoSensor;
SELECT UnidadeID, DescricaoUnidade FROM Unidade;
SELECT ViaAplicacaoID, DesignacaoViaAplicacao FROM ViaAplicacao;
SELECT ViaAplicacaoID, FatorProducaoID FROM ViaAplicacao_FatorProdução;

