INSERT INTO AplicacaoFatorProducao(OperacaoID, QuantidadeFatorProducao, Area, FatorProducaoID, CultivoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Colheita(OperacaoID, QuantidadeProduto, ProdutoID, CultivoID) VALUES (?, ?, ?, ?);
INSERT INTO Cultivo(CultivoID, CulturaID, ParcelaID, DataInicio, DataFim, Quantidade, UnidadeID, EstadoFenologicoID) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO Cultura(CulturaID, Variedade, EspecieVegetalID) VALUES (?, ?, ?);
INSERT INTO Edificio(EdificioID, DesignacaoEdificio, Area, UnidadeID, TipoEdificioID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Elemento(ElementoID, Designacao, Simbolo) VALUES (?, ?, ?);
INSERT INTO EspecieVegetal(EspecieVegetalID, DesignacaoEspecie, NomeComum, TipoCulturaID) VALUES (?, ?, ?, ?);
INSERT INTO EstadoFenologico(EstadoFenologicoID, Designacao) VALUES (?, ?);
INSERT INTO Fabricante(FabricanteID, DesignacaoFabricante) VALUES (?, ?);
INSERT INTO FatorProducao(FatorProducaoID, NomeComercial, FabricanteID, FormatoID, TipoFatorProducaoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO FatorProducao_Elemento(ElementoID, FatorProducaoID, Quantidade) VALUES (?, ?, ?);
INSERT INTO FormaDispersao(FormaDispersaoID, DesignacaoFormaDispersao) VALUES (?, ?);
INSERT INTO Formato(FormatoID, DescricaoFormato) VALUES (?, ?);
INSERT INTO Grandeza(GrandezaID, DesignacaoGrandeza) VALUES (?, ?);
INSERT INTO IncorporacaoSolo(OperacaoID, Area, CultivoID) VALUES (?, ?, ?);
INSERT INTO Log(LogID, TipoOperacao, DataCriacao, DataRealizacao, Estado, ParcelaID, CultivoID, SetorID, Quantidade, Area, Hora, Modo, UnidadeID, ProdutoID, FatorProducaoID, ReceitaID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO Medição(MedicaoID, Timestamp, ValorMedido, UnidadeID, SensorSoloID, SensorMeteorologicoID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO MobilizacaoSolo(OperacaoID, Area, ParcelaID) VALUES (?, ?, ?);
INSERT INTO Monda(OperacaoID, Modo, Area, CultivoID, FatorProducaoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Operacao(OperacaoID, DataRealizacao, DataCriacao, TipoOperacao, Estado) VALUES (?, ?, ?, ?, ?);
INSERT INTO Parcela(ParcelaID, Designacao, Area, UnidadeID) VALUES (?, ?, ?, ?);
INSERT INTO Parcela_SensorSolo(ParcelaID, SensorSoloID) VALUES (?, ?);
INSERT INTO PlanoAgricola(PlanoAgricolaID, Ano) VALUES (?, ?);
INSERT INTO PlanoColheita(PlanoColheitaID, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CultivoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO PlanoCorrecaoMineral(PlanoCorrecaoMineralID, PlanoAgricolaID, CultivoID) VALUES (?, ?, ?);
INSERT INTO PlanoFertilizacao(PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CultivoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO PlanoFertilizacao_FatorProducao(PlanoFertilizacaoID, FatorProducaoID) VALUES (?, ?);
INSERT INTO PlanoRega(PlanoRegaID, QuantidadeRega, Periodicidade, PlanoAgricolaID, SetorID) VALUES (?, ?, ?, ?, ?);
INSERT INTO PlanoRega_FatorProducao(PlanoRegaID, FatorProducaoID) VALUES (?, ?);
INSERT INTO Plantacao(OperacaoID, Quantidade, CultivoID) VALUES (?, ?, ?);
INSERT INTO Poda(OperacaoID, Quantidade, CultivoID) VALUES (?, ?, ?);
INSERT INTO Produto(ProdutoID, DesignacaoProduto, CulturaID) VALUES (?, ?, ?);
INSERT INTO Receita(ReceitaID) VALUES (?);
INSERT INTO Receita_FatorProducao(ReceitaID, FatorProducaoID, Quantidade, UnidadeID) VALUES (?, ?, ?, ?);
INSERT INTO Rega(OperacaoID, Hora, Duracao, SetorID, ParcelaID, ReceitaID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO Semeadura(OperacaoID, Quantidade, Area, CultivoID) VALUES (?, ?, ?, ?);
INSERT INTO SensorMeteorologico(SensorMeteorologicoID, TipoSensorID) VALUES (?, ?);
INSERT INTO SensorSolo(SensorSoloID, TipoSensorID) VALUES (?, ?);
INSERT INTO Setor(SetorID, Caudal, DataInicio, DataFim, FormaDispersaoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Setor_Parcela(SetorID, ParcelaID) VALUES (?, ?);
INSERT INTO TipoCultura(TipoCulturaID, DesignacaoTipoCultura) VALUES (?, ?);
INSERT INTO TipoEdificio(TipoEdificioID, DesignacaoTipoEdificio) VALUES (?, ?);
INSERT INTO TipoFatorProducao(TipoFatorProducaoID, DescricaoTipoFatorProducao) VALUES (?, ?);
INSERT INTO TipoSensor(TipoSensorID, TipoSensor, GrandezaID) VALUES (?, ?, ?);
INSERT INTO Unidade(UnidadeID, DescricaoUnidade) VALUES (?, ?);
INSERT INTO ViaAplicacao(ViaAplicacaoID, DesignacaoViaAplicacao) VALUES (?, ?);
INSERT INTO ViaAplicacao_FatorProducao(ViaAplicacaoID, FatorProducaoID) VALUES (?, ?);

