UPDATE AplicacaoFatorProducao SET QuantidadeFatorProducao = ?, Area = ?, FatorProducaoID = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Colheita SET QuantidadeProduto = ?, ProdutoID = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Cultivo SET CulturaID = ?, ParcelaID = ?, DataInicio = ?, DataFim = ?, Quantidade = ?, UnidadeID = ?, EstadoFenologicoID = ? WHERE CultivoID = ?;
UPDATE Cultura SET Variedade = ?, EspecieVegetalID = ? WHERE CulturaID = ?;
UPDATE Edificio SET DesignacaoEdificio = ?, Area = ?, UnidadeID = ?, TipoEdificioID = ? WHERE EdificioID = ?;
UPDATE Elemento SET Designacao = ?, Simbolo = ? WHERE ElementoID = ?;
UPDATE EspecieVegetal SET DesignacaoEspecie = ?, NomeComum = ?, TipoCulturaID = ? WHERE EspecieVegetalID = ?;
UPDATE EstadoFenologico SET Designacao = ? WHERE EstadoFenologicoID = ?;
UPDATE Fabricante SET DesignacaoFabricante = ? WHERE FabricanteID = ?;
UPDATE FatorProducao SET NomeComercial = ?, FabricanteID = ?, FormatoID = ?, TipoFatorProducaoID = ? WHERE FatorProducaoID = ?;
UPDATE FatorProducao_Elemento SET Quantidade = ? WHERE ElementoID = ? AND FatorProducaoID = ?;
UPDATE FormaDispersao SET DesignacaoFormaDispersao = ? WHERE FormaDispersaoID = ?;
UPDATE Formato SET DescricaoFormato = ? WHERE FormatoID = ?;
UPDATE Grandeza SET DesignacaoGrandeza = ? WHERE GrandezaID = ?;
UPDATE IncorporacaoSolo SET Area = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Log SET TipoOperacao = ?, DataCriacao = ?, DataRealizacao = ?, Estado = ?, ParcelaID = ?, CultivoID = ?, SetorID = ?, Quantidade = ?, Area = ?, Hora = ?, Modo = ?, UnidadeID = ?, ProdutoID = ?, FatorProducaoID = ?, ReceitaID = ? WHERE LogID = ?;
UPDATE Medição SET Timestamp = ?, ValorMedido = ?, UnidadeID = ?, SensorSoloID = ?, SensorMeteorologicoID = ? WHERE MedicaoID = ?;
UPDATE MobilizacaoSolo SET Area = ?, ParcelaID = ? WHERE OperacaoID = ?;
UPDATE Monda SET Modo = ?, Area = ?, CultivoID = ?, FatorProducaoID = ? WHERE OperacaoID = ?;
UPDATE Operacao SET DataRealizacao = ?, DataCriacao = ?, TipoOperacao = ?, Estado = ? WHERE OperacaoID = ?;
UPDATE Parcela SET Designacao = ?, Area = ?, UnidadeID = ? WHERE ParcelaID = ?;
UPDATE Parcela_SensorSolo SET  WHERE ParcelaID = ? AND SensorSoloID = ?;
UPDATE PlanoAgricola SET Ano = ? WHERE PlanoAgricolaID = ?;
UPDATE PlanoColheita SET DataPrevista = ?, QuantidadePrevista = ?, PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoColheitaID = ?;
UPDATE PlanoCorrecaoMineral SET PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoCorrecaoMineralID = ?;
UPDATE PlanoFertilizacao SET DataPrevista = ?, ViaAplicacaoID = ?, PlanoAgricolaID = ?, CultivoID = ? WHERE PlanoFertilizacaoID = ?;
UPDATE PlanoFertilizacao_FatorProducao SET  WHERE PlanoFertilizacaoID = ? AND FatorProducaoID = ?;
UPDATE PlanoRega SET QuantidadeRega = ?, Periodicidade = ?, PlanoAgricolaID = ?, SetorID = ? WHERE PlanoRegaID = ?;
UPDATE PlanoRega_FatorProducao SET  WHERE PlanoRegaID = ? AND FatorProducaoID = ?;
UPDATE Plantacao SET Quantidade = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Poda SET Quantidade = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE Produto SET DesignacaoProduto = ?, CulturaID = ? WHERE ProdutoID = ?;
UPDATE Receita SET  WHERE ReceitaID = ?;
UPDATE Receita_FatorProducao SET Quantidade = ?, UnidadeID = ? WHERE ReceitaID = ? AND FatorProducaoID = ?;
UPDATE Rega SET Hora = ?, Duracao = ?, SetorID = ?, ParcelaID = ?, ReceitaID = ? WHERE OperacaoID = ?;
UPDATE Semeadura SET Quantidade = ?, Area = ?, CultivoID = ? WHERE OperacaoID = ?;
UPDATE SensorMeteorologico SET TipoSensorID = ? WHERE SensorMeteorologicoID = ?;
UPDATE SensorSolo SET TipoSensorID = ? WHERE SensorSoloID = ?;
UPDATE Setor SET Caudal = ?, DataInicio = ?, DataFim = ?, FormaDispersaoID = ? WHERE SetorID = ?;
UPDATE Setor_Parcela SET  WHERE SetorID = ? AND ParcelaID = ?;
UPDATE TipoCultura SET DesignacaoTipoCultura = ? WHERE TipoCulturaID = ?;
UPDATE TipoEdificio SET DesignacaoTipoEdificio = ? WHERE TipoEdificioID = ?;
UPDATE TipoFatorProducao SET DescricaoTipoFatorProducao = ? WHERE TipoFatorProducaoID = ?;
UPDATE TipoSensor SET TipoSensor = ?, GrandezaID = ? WHERE TipoSensorID = ?;
UPDATE Unidade SET DescricaoUnidade = ? WHERE UnidadeID = ?;
UPDATE ViaAplicacao SET DesignacaoViaAplicacao = ? WHERE ViaAplicacaoID = ?;
UPDATE ViaAplicacao_FatorProducao SET  WHERE ViaAplicacaoID = ? AND FatorProducaoID = ?;

