SELECT OperacaoID, QuantidadeFatorProducao, Area, FatorProducaoID, CultivoID FROM AplicacaoFatorProducao;
SELECT OperacaoID, QuantidadeProduto, ProdutoID, CultivoID FROM Colheita;
SELECT CultivoID, CulturaID, ParcelaID, DataInicio, DataFim, Quantidade, UnidadeID, EstadoFenologicoID FROM Cultivo;
SELECT CulturaID, Variedade, EspecieVegetalID FROM Cultura;
SELECT EdificioID, DesignacaoEdificio, Area, UnidadeID, TipoEdificioID FROM Edificio;
SELECT ElementoID, Designacao, Simbolo FROM Elemento;
SELECT EspecieVegetalID, DesignacaoEspecie, NomeComum, TipoCulturaID FROM EspecieVegetal;
SELECT EstadoFenologicoID, Designacao FROM EstadoFenologico;
SELECT FabricanteID, DesignacaoFabricante FROM Fabricante;
SELECT FatorProducaoID, NomeComercial, FabricanteID, FormatoID, TipoFatorProducaoID FROM FatorProducao;
SELECT ElementoID, FatorProducaoID, Quantidade FROM FatorProducao_Elemento;
SELECT FormaDispersaoID, DesignacaoFormaDispersao FROM FormaDispersao;
SELECT FormatoID, DescricaoFormato FROM Formato;
SELECT GrandezaID, DesignacaoGrandeza FROM Grandeza;
SELECT OperacaoID, Area, CultivoID FROM IncorporacaoSolo;
SELECT LogID, TipoOperacao, DataCriacao, DataRealizacao, Estado, ParcelaID, CultivoID, SetorID, Quantidade, Area, Hora, Modo, UnidadeID, ProdutoID, FatorProducaoID, ReceitaID FROM Log;
SELECT MedicaoID, Timestamp, ValorMedido, UnidadeID, SensorSoloID, SensorMeteorologicoID FROM Medição;
SELECT OperacaoID, Area, ParcelaID FROM MobilizacaoSolo;
SELECT OperacaoID, Modo, Area, CultivoID, FatorProducaoID FROM Monda;
SELECT OperacaoID, DataRealizacao, DataCriacao, TipoOperacao, Estado FROM Operacao;
SELECT ParcelaID, Designacao, Area, UnidadeID FROM Parcela;
SELECT ParcelaID, SensorSoloID FROM Parcela_SensorSolo;
SELECT PlanoAgricolaID, Ano FROM PlanoAgricola;
SELECT PlanoColheitaID, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CultivoID FROM PlanoColheita;
SELECT PlanoCorrecaoMineralID, PlanoAgricolaID, CultivoID FROM PlanoCorrecaoMineral;
SELECT PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CultivoID FROM PlanoFertilizacao;
SELECT PlanoFertilizacaoID, FatorProducaoID FROM PlanoFertilizacao_FatorProducao;
SELECT PlanoRegaID, QuantidadeRega, Periodicidade, PlanoAgricolaID, SetorID FROM PlanoRega;
SELECT PlanoRegaID, FatorProducaoID FROM PlanoRega_FatorProducao;
SELECT OperacaoID, Quantidade, CultivoID FROM Plantacao;
SELECT OperacaoID, Quantidade, CultivoID FROM Poda;
SELECT ProdutoID, DesignacaoProduto, CulturaID FROM Produto;
SELECT ReceitaID FROM Receita;
SELECT ReceitaID, FatorProducaoID, Quantidade, UnidadeID FROM Receita_FatorProducao;
SELECT OperacaoID, Hora, Duracao, SetorID, ParcelaID, ReceitaID FROM Rega;
SELECT OperacaoID, Quantidade, Area, CultivoID FROM Semeadura;
SELECT SensorMeteorologicoID, TipoSensorID FROM SensorMeteorologico;
SELECT SensorSoloID, TipoSensorID FROM SensorSolo;
SELECT SetorID, Caudal, DataInicio, DataFim, FormaDispersaoID FROM Setor;
SELECT SetorID, ParcelaID FROM Setor_Parcela;
SELECT TipoCulturaID, DesignacaoTipoCultura FROM TipoCultura;
SELECT TipoEdificioID, DesignacaoTipoEdificio FROM TipoEdificio;
SELECT TipoFatorProducaoID, DescricaoTipoFatorProducao FROM TipoFatorProducao;
SELECT TipoSensorID, TipoSensor, GrandezaID FROM TipoSensor;
SELECT UnidadeID, DescricaoUnidade FROM Unidade;
SELECT ViaAplicacaoID, DesignacaoViaAplicacao FROM ViaAplicacao;
SELECT ViaAplicacaoID, FatorProducaoID FROM ViaAplicacao_FatorProducao;

