-- Criar tabela de log de operações
CREATE TABLE OPERACAO_LOG (
    LOGID        NUMBER(10)     PRIMARY KEY,
    OPERACAOID   NUMBER(10)     NOT NULL,
    TIPOOPERACAO NVARCHAR2(255) NOT NULL,
    DATAREALIZACAO DATE          NOT NULL,
    PARCELAID    NUMBER(10),
    LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE TRIGGER OPERACAO_LOG_TRIGGER
    AFTER INSERT OR UPDATE ON OPERACAO
    FOR EACH ROW
BEGIN
    IF :NEW.TIPOOPERACAO = 'Monda' THEN
        INSERT INTO LOG (OPERACAOID, TIPOOPERACAO, DATAREALIZACAO, PARCELAID)
        VALUES (:NEW.OPERACAOID, :NEW.TIPOOPERACAO, :NEW.DATAREALIZACAO, :NEW.PARCELAID);
    ELSIF :NEW.TIPOOPERACAO = 'Plantação' THEN
        INSERT INTO LOG (OPERACAOID, TIPOOPERACAO, DATAREALIZACAO, PARCELAID)
        VALUES (:NEW.OPERACAOID, :NEW.TIPOOPERACAO, :NEW.DATAREALIZACAO, :NEW.PARCELAID);
END IF;
END;