SELECT OperacaoID FROM Colheita;
SELECT OperacaoID, ProdutoID, QuantidadeColhida FROM Colheita_Produto;
SELECT CulturaID, ParcelaID, DataInicio, DataFim FROM Cultivo;
SELECT CulturaID, EspecieVegetal, TipoCulturaID FROM Cultura;
SELECT EdificioID, DesignacaoEdificio, Area, IntalacaoAgricolaID, TipoEdificioID FROM Edifício;
SELECT ElementoID, Nome FROM Elemento;
SELECT EstacaoMeteorologicaID FROM EstaçãoMeteorologica;
SELECT FabricanteID, DesignacaoFabricante FROM Fabricante;
SELECT FatorProducaoID, NomeComercial, FabricanteID, FormulaID, TipoFatorProducaoID FROM FatorProdução;
SELECT OperacaoID FROM Fertilizacao;
SELECT OperacaoID, FatorProducaoID, Quantidade FROM Fertilizacao_FatorProdução;
SELECT OperacaoID, ViaAplicacaoID FROM Fertilizacao_ViaAplicacao;
SELECT FichaTecnicaID, FatorProducaoID FROM FichaTecnica;
SELECT FichaTecnicaID, ElementoID, Quantidade FROM FichaTecnica_Elemento;
SELECT FormatoID, DescricaoFormato FROM Formato;
SELECT GrandezaID, DesignacaoGrandeza FROM Grandeza;
SELECT MedicaoID, ValorMedido, EstacaoMeteorologicaID, TipoSensorID, "Caderno de CampoCadernoCampoID" FROM Medição;
SELECT OperacaoID, DataRealizacao, CadernoCampoID, CulturaID, ParcelaID FROM Operacao;
SELECT ParcelaID, Designacao, Area, IntalacaoAgricolaID FROM Parcela;
SELECT PlanoAgricolaID, Ano, "Instalação AgricolaIntalacaoAgricolaID" FROM PlanoAgricola;
SELECT PlanoColheita, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoColheita;
SELECT PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoFertilizacao;
SELECT PlanoFertilizacaoID, FatorProducaoID, Quantidade FROM PlanoFertilizacao_FatorProdução;
SELECT PlanoRegaID, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoRega;
SELECT OperacaoID, Quantidade FROM Plantacao;
SELECT ProdutoID, DesignacaoProduto FROM Produto;
SELECT OperacaoID, Quantidade, Hora FROM Rega;
SELECT OperacaoID, Quantidade FROM Sementeira;
SELECT EstacaoMeteorologicaID, TipoSensorID, CulturaID, ParcelaID FROM Sensor;
SELECT TipoEdificioID, DesignacaoTipoEdificio FROM "Tipo Edificio";
SELECT TipoCulturaID, DesignacaoTipoCultura FROM TipoCultura;
SELECT TipoFatorProducaoID, DescricaoTipoFatorProducao FROM TipoFatorProducao;
SELECT TipoSensorID, TipoSensor, GrandezaID FROM TipoSensor;
SELECT ViaAplicacaoID, DesignacaoViaAplicacao FROM ViaAplicacao;

