SELECT CulturaID, ParcelaID, DataInicio, DataFim, Quantidade, UnidadeID FROM Cultivo;
SELECT CulturaID, Variedade, EspecieVegetalID, EpocaSementeiraPlantacao, EpocaPoda, EpocaFloracao, EpocaColheita FROM Cultura;
SELECT EdificioID, DesignacaoEdificio, Area, UnidadeID, TipoEdificioID FROM Edifício;
SELECT ElementoID, Nome FROM Elemento;
SELECT EspecieVegetalID, DesignacaoEspecie, NomeComum, TipoCulturaID FROM EspecieVegetal;
SELECT EstacaoMeteorologicaID FROM EstaçãoMeteorologica;
SELECT FabricanteID, DesignacaoFabricante FROM Fabricante;
SELECT ElementoID, FatorProducaoID, Quantidade, UnidadeID FROM FatorProducao_Elemento;
SELECT FatorProducaoID, NomeComercial, FabricanteID, FormatoID, TipoFatorProducaoID FROM FatorProdução;
SELECT FormatoID, DescricaoFormato FROM Formato;
SELECT GrandezaID, DesignacaoGrandeza FROM Grandeza;
SELECT MedicaoID, ValorMedido, EstacaoMeteorologicaID, TipoSensorID FROM Medição;
SELECT OperacaoID, CulturaID, ParcelaID, TipoOperacaoID, DataRealizacao, Quantidade, UnidadeID, FatorProducaoID FROM Operacao;
SELECT OperacaoOperacaoID, ProdutoProdutoID, Quantidade, UnidadeID FROM Operacao_Produto;
SELECT ParcelaID, Designacao, Area, UnidadeID FROM Parcela;
SELECT PlanoAgricolaID, Ano FROM PlanoAgricola;
SELECT PlanoColheita, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoColheita;
SELECT PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoFertilizacao;
SELECT PlanoRegaID, PlanoAgricolaID, CulturaID, ParcelaID FROM PlanoRega;
SELECT ProdutoID, DesignacaoProduto FROM Produto;
SELECT EstacaoMeteorologicaID, TipoSensorID, CulturaID, ParcelaID FROM Sensor;
SELECT TipoCulturaID, DesignacaoTipoCultura FROM TipoCultura;
SELECT TipoEdificioID, DesignacaoTipoEdificio FROM TipoEdificio;
SELECT TipoFatorProducaoID, DescricaoTipoFatorProducao FROM TipoFatorProducao;
SELECT TipoOperacaoID, DesignacaoTipoOperacao FROM TipoOperacao;
SELECT TipoSensorID, TipoSensor, GrandezaID FROM TipoSensor;
SELECT UnidadeID, DescricaoUnidade FROM Unidade;
SELECT ViaAplicacaoID, DesignacaoViaAplicacao FROM ViaAplicacao;
SELECT ViaAplicacaoID, FatorProducaoID FROM ViaAplicacao_FatorProdução;

