INSERT INTO Cultivo(CulturaID, ParcelaID, DataInicio, DataFim, Quantidade, UnidadeID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO Cultura(CulturaID, Variedade, EspecieVegetalID, EpocaSementeiraPlantacao, EpocaPoda, EpocaFloracao, EpocaColheita) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO Edificio(EdificioID, DesignacaoEdificio, Area, UnidadeID, TipoEdificioID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Elemento(ElementoID, Nome) VALUES (?, ?);
INSERT INTO EspecieVegetal(EspecieVegetalID, DesignacaoEspecie, NomeComum, TipoCulturaID) VALUES (?, ?, ?, ?);
INSERT INTO EstaçãoMeteorologica(EstacaoMeteorologicaID) VALUES (?);
INSERT INTO Fabricante(FabricanteID, DesignacaoFabricante) VALUES (?, ?);
INSERT INTO FatorProducao_Elemento(ElementoID, FatorProducaoID, Quantidade, UnidadeID) VALUES (?, ?, ?, ?);
INSERT INTO FatorProdução(FatorProducaoID, NomeComercial, FabricanteID, FormatoID, TipoFatorProducaoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Formato(FormatoID, DescricaoFormato) VALUES (?, ?);
INSERT INTO Grandeza(GrandezaID, DesignacaoGrandeza) VALUES (?, ?);
INSERT INTO Medição(MedicaoID, ValorMedido, EstacaoMeteorologicaID, TipoSensorID) VALUES (?, ?, ?, ?);
INSERT INTO Operacao(OperacaoID, CulturaID, ParcelaID, TipoOperacaoID, DataRealizacao, Quantidade, UnidadeID, FatorProducaoID) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO Operacao_Produto(OperacaoOperacaoID, ProdutoProdutoID, Quantidade, UnidadeID) VALUES (?, ?, ?, ?);
INSERT INTO Parcela(ParcelaID, Designacao, Area, UnidadeID) VALUES (?, ?, ?, ?);
INSERT INTO PlanoAgricola(PlanoAgricolaID, Ano) VALUES (?, ?);
INSERT INTO PlanoColheita(PlanoColheita, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO PlanoFertilizacao(PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO PlanoRega(PlanoRegaID, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?);
INSERT INTO Produto(ProdutoID, DesignacaoProduto) VALUES (?, ?);
INSERT INTO Sensor(EstacaoMeteorologicaID, TipoSensorID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?);
INSERT INTO TipoCultura(TipoCulturaID, DesignacaoTipoCultura) VALUES (?, ?);
INSERT INTO TipoEdificio(TipoEdificioID, DesignacaoTipoEdificio) VALUES (?, ?);
INSERT INTO TipoFatorProducao(TipoFatorProducaoID, DescricaoTipoFatorProducao) VALUES (?, ?);
INSERT INTO TipoOperacao(TipoOperacaoID, DesignacaoTipoOperacao) VALUES (?, ?);
INSERT INTO TipoSensor(TipoSensorID, TipoSensor, GrandezaID) VALUES (?, ?, ?);
INSERT INTO Unidade(UnidadeID, DescricaoUnidade) VALUES (?, ?);
INSERT INTO ViaAplicacao(ViaAplicacaoID, DesignacaoViaAplicacao) VALUES (?, ?);
INSERT INTO ViaAplicacao_FatorProdução(ViaAplicacaoID, FatorProducaoID) VALUES (?, ?);

