DELETE FROM Colheita WHERE OperacaoID = ?;
DELETE FROM Colheita_Produto WHERE OperacaoID = ? AND ProdutoID = ?;
DELETE FROM Cultivo WHERE CulturaID = ? AND ParcelaID = ?;
DELETE FROM Cultura WHERE CulturaID = ?;
DELETE FROM Edifício WHERE EdificioID = ?;
DELETE FROM Elemento WHERE ElementoID = ?;
DELETE FROM EstaçãoMeteorologica WHERE EstacaoMeteorologicaID = ?;
DELETE FROM Fabricante WHERE FabricanteID = ?;
DELETE FROM FatorProdução WHERE FatorProducaoID = ?;
DELETE FROM Fertilizacao WHERE OperacaoID = ?;
DELETE FROM Fertilizacao_FatorProdução WHERE OperacaoID = ? AND FatorProducaoID = ?;
DELETE FROM Fertilizacao_ViaAplicacao WHERE OperacaoID = ? AND ViaAplicacaoID = ?;
DELETE FROM FichaTecnica WHERE FichaTecnicaID = ?;
DELETE FROM FichaTecnica_Elemento WHERE FichaTecnicaID = ? AND ElementoID = ?;
DELETE FROM Formato WHERE FormatoID = ?;
DELETE FROM Grandeza WHERE GrandezaID = ?;
DELETE FROM Medição WHERE MedicaoID = ?;
DELETE FROM Operacao WHERE OperacaoID = ?;
DELETE FROM Parcela WHERE ParcelaID = ?;
DELETE FROM PlanoAgricola WHERE PlanoAgricolaID = ?;
DELETE FROM PlanoColheita WHERE PlanoColheita = ?;
DELETE FROM PlanoFertilizacao WHERE PlanoFertilizacaoID = ?;
DELETE FROM PlanoFertilizacao_FatorProdução WHERE PlanoFertilizacaoID = ? AND FatorProducaoID = ?;
DELETE FROM PlanoRega WHERE PlanoRegaID = ?;
DELETE FROM Plantacao WHERE OperacaoID = ?;
DELETE FROM Produto WHERE ProdutoID = ?;
DELETE FROM Rega WHERE OperacaoID = ?;
DELETE FROM Sementeira WHERE OperacaoID = ?;
DELETE FROM Sensor WHERE EstacaoMeteorologicaID = ? AND TipoSensorID = ?;
DELETE FROM "Tipo Edificio" WHERE TipoEdificioID = ?;
DELETE FROM TipoCultura WHERE TipoCulturaID = ?;
DELETE FROM TipoFatorProducao WHERE TipoFatorProducaoID = ?;
DELETE FROM TipoSensor WHERE TipoSensorID = ?;
DELETE FROM ViaAplicacao WHERE ViaAplicacaoID = ?;

