INSERT INTO Colheita(OperacaoID) VALUES (?);
INSERT INTO Colheita_Produto(OperacaoID, ProdutoID, QuantidadeColhida) VALUES (?, ?, ?);
INSERT INTO Cultivo(CulturaID, ParcelaID, DataInicio, DataFim) VALUES (?, ?, ?, ?);
INSERT INTO Cultura(CulturaID, EspecieVegetal, TipoCulturaID) VALUES (?, ?, ?);
INSERT INTO Edifício(EdificioID, DesignacaoEdificio, Area, TipoEdificioID) VALUES (?, ?, ?, ?);
INSERT INTO Elemento(ElementoID, Nome) VALUES (?, ?);
INSERT INTO EstaçãoMeteorologica(EstacaoMeteorologicaID) VALUES (?);
INSERT INTO Fabricante(FabricanteID, DesignacaoFabricante) VALUES (?, ?);
INSERT INTO FatorProducao_Elemento(ElementoID, Quantidade, FatorProduçãoFatorProducaoID) VALUES (?, ?, ?);
INSERT INTO FatorProdução(FatorProducaoID, NomeComercial, FabricanteID, FormulaID, TipoFatorProducaoID) VALUES (?, ?, ?, ?, ?);
INSERT INTO Fertilizacao(OperacaoID) VALUES (?);
INSERT INTO Fertilizacao_FatorProdução(OperacaoID, FatorProducaoID, Quantidade) VALUES (?, ?, ?);
INSERT INTO Fertilizacao_ViaAplicacao(OperacaoID, ViaAplicacaoID) VALUES (?, ?);
INSERT INTO Formato(FormatoID, DescricaoFormato) VALUES (?, ?);
INSERT INTO Grandeza(GrandezaID, DesignacaoGrandeza) VALUES (?, ?);
INSERT INTO Medição(MedicaoID, ValorMedido, EstacaoMeteorologicaID, TipoSensorID) VALUES (?, ?, ?, ?);
INSERT INTO Operacao(OperacaoID, DataRealizacao, CulturaID, ParcelaID) VALUES (?, ?, ?, ?);
INSERT INTO Parcela(ParcelaID, Designacao, Area) VALUES (?, ?, ?);
INSERT INTO PlanoAgricola(PlanoAgricolaID, Ano, "Instalação AgricolaIntalacaoAgricolaID") VALUES (?, ?, ?);
INSERT INTO PlanoColheita(PlanoColheita, DataPrevista, QuantidadePrevista, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO PlanoFertilizacao(PlanoFertilizacaoID, DataPrevista, ViaAplicacaoID, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO PlanoRega(PlanoRegaID, PlanoAgricolaID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?);
INSERT INTO Plantacao(OperacaoID, Quantidade) VALUES (?, ?);
INSERT INTO Produto(ProdutoID, DesignacaoProduto) VALUES (?, ?);
INSERT INTO Rega(OperacaoID, Quantidade, Hora) VALUES (?, ?, ?);
INSERT INTO Sementeira(OperacaoID, Quantidade) VALUES (?, ?);
INSERT INTO Sensor(EstacaoMeteorologicaID, TipoSensorID, CulturaID, ParcelaID) VALUES (?, ?, ?, ?);
INSERT INTO TipoCultura(TipoCulturaID, DesignacaoTipoCultura) VALUES (?, ?);
INSERT INTO TipoEdificio(TipoEdificioID, DesignacaoTipoEdificio) VALUES (?, ?);
INSERT INTO TipoFatorProducao(TipoFatorProducaoID, DescricaoTipoFatorProducao) VALUES (?, ?);
INSERT INTO TipoSensor(TipoSensorID, TipoSensor, GrandezaID) VALUES (?, ?, ?);
INSERT INTO ViaAplicacao(ViaAplicacaoID, DesignacaoViaAplicacao) VALUES (?, ?);

