UPDATE AplicacaoFitofarmaco SET  WHERE OperacaoID = ?;
UPDATE Colheita SET QuantidadeColhida = ?, UnidadeID = ?, ProdutoID = ? WHERE OperacaoID = ?;
UPDATE Cultivo SET DataInicio = ?, DataFim = ?, Quantidade = ?, UnidadeID = ? WHERE CulturaID = ? AND ParcelaID = ?;
UPDATE Cultura SET Variedade = ?, EspecieVegetalID = ?, EpocaSementeiraPlantacao = ?, EpocaPoda = ?, EpocaFloracao = ?, EpocaColheita = ? WHERE CulturaID = ?;
UPDATE Edifício SET DesignacaoEdificio = ?, Area = ?, UnidadeID = ?, TipoEdificioID = ? WHERE EdificioID = ?;
UPDATE Elemento SET Nome = ? WHERE ElementoID = ?;
UPDATE EspecieVegetal SET DesignacaoEspecie = ?, NomeComum = ?, TipoCulturaID = ? WHERE EspecieVegetalID = ?;
UPDATE EstaçãoMeteorologica SET  WHERE EstacaoMeteorologicaID = ?;
UPDATE Fabricante SET DesignacaoFabricante = ? WHERE FabricanteID = ?;
UPDATE FatorProducao_Elemento SET Quantidade = ?, UnidadeID = ? WHERE ElementoID = ? AND FatorProducaoID = ?;
UPDATE FatorProdução SET NomeComercial = ?, FabricanteID = ?, FormatoID = ?, TipoFatorProducaoID = ? WHERE FatorProducaoID = ?;
UPDATE Fertilizacao SET  WHERE OperacaoID = ?;
UPDATE Formato SET DescricaoFormato = ? WHERE FormatoID = ?;
UPDATE Grandeza SET DesignacaoGrandeza = ? WHERE GrandezaID = ?;
UPDATE IncorporacaoSolo SET Quantidade = ?, UnidadeID = ? WHERE OperacaoID = ?;
UPDATE Medição SET ValorMedido = ?, EstacaoMeteorologicaID = ?, TipoSensorID = ? WHERE MedicaoID = ?;
UPDATE Operacao SET DataRealizacao = ?, CulturaID = ?, ParcelaID = ? WHERE OperacaoID = ?;
UPDATE Operacao_FatorProdução SET Quantidade = ?, UnidadeID = ?, AplicacaoFitofarmacoOperacaoID = ? WHERE OperacaoID = ? AND FatorProducaoID = ?;
UPDATE Parcela SET Designacao = ?, Area = ?, UnidadeID = ? WHERE ParcelaID = ?;
UPDATE PlanoAgricola SET Ano = ?, "Instalação AgricolaIntalacaoAgricolaID" = ? WHERE PlanoAgricolaID = ?;
UPDATE PlanoColheita SET DataPrevista = ?, QuantidadePrevista = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoColheita = ?;
UPDATE PlanoFertilizacao SET DataPrevista = ?, ViaAplicacaoID = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoFertilizacaoID = ?;
UPDATE PlanoRega SET PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoRegaID = ?;
UPDATE Plantacao SET Quantidade = ?, UnidadeID = ? WHERE OperacaoID = ?;
UPDATE Poda SET Quantidade = ?, UnidadeUnidadeID = ? WHERE OperacaoID = ?;
UPDATE Produto SET DesignacaoProduto = ? WHERE ProdutoID = ?;
UPDATE Rega SET Quantidade = ?, Hora = ?, UnidadeID = ? WHERE OperacaoID = ?;
UPDATE Sementeira SET Quantidade = ?, UnidadeID = ? WHERE OperacaoID = ?;
UPDATE Sensor SET CulturaID = ?, ParcelaID = ? WHERE EstacaoMeteorologicaID = ? AND TipoSensorID = ?;
UPDATE TipoCultura SET DesignacaoTipoCultura = ? WHERE TipoCulturaID = ?;
UPDATE TipoEdificio SET DesignacaoTipoEdificio = ? WHERE TipoEdificioID = ?;
UPDATE TipoFatorProducao SET DescricaoTipoFatorProducao = ? WHERE TipoFatorProducaoID = ?;
UPDATE TipoSensor SET TipoSensor = ?, GrandezaID = ? WHERE TipoSensorID = ?;
UPDATE Unidade SET DescricaoUnidade = ? WHERE UnidadeID = ?;
UPDATE ViaAplicacao SET DesignacaoViaAplicacao = ? WHERE ViaAplicacaoID = ?;
UPDATE ViaAplicacao_FatorProdução SET  WHERE ViaAplicacaoID = ? AND FatorProducaoID = ?;

