UPDATE Colheita SET  WHERE OperacaoID = ?;
UPDATE Colheita_Produto SET QuantidadeColhida = ? WHERE OperacaoID = ? AND ProdutoID = ?;
UPDATE Cultivo SET DataInicio = ?, DataFim = ? WHERE CulturaID = ? AND ParcelaID = ?;
UPDATE Cultura SET EspecieVegetal = ?, TipoCulturaID = ? WHERE CulturaID = ?;
UPDATE Edifício SET DesignacaoEdificio = ?, Area = ?, IntalacaoAgricolaID = ?, TipoEdificioID = ? WHERE EdificioID = ?;
UPDATE Elemento SET Nome = ? WHERE ElementoID = ?;
UPDATE EstaçãoMeteorologica SET  WHERE EstacaoMeteorologicaID = ?;
UPDATE Fabricante SET DesignacaoFabricante = ? WHERE FabricanteID = ?;
UPDATE FatorProdução SET NomeComercial = ?, FabricanteID = ?, FormulaID = ?, TipoFatorProducaoID = ? WHERE FatorProducaoID = ?;
UPDATE Fertilizacao SET  WHERE OperacaoID = ?;
UPDATE Fertilizacao_FatorProdução SET Quantidade = ? WHERE OperacaoID = ? AND FatorProducaoID = ?;
UPDATE Fertilizacao_ViaAplicacao SET  WHERE OperacaoID = ? AND ViaAplicacaoID = ?;
UPDATE FichaTecnica SET FatorProducaoID = ? WHERE FichaTecnicaID = ?;
UPDATE FichaTecnica_Elemento SET Quantidade = ? WHERE FichaTecnicaID = ? AND ElementoID = ?;
UPDATE Formato SET DescricaoFormato = ? WHERE FormatoID = ?;
UPDATE Grandeza SET DesignacaoGrandeza = ? WHERE GrandezaID = ?;
UPDATE Medição SET ValorMedido = ?, EstacaoMeteorologicaID = ?, TipoSensorID = ?, "Caderno de CampoCadernoCampoID" = ? WHERE MedicaoID = ?;
UPDATE Operacao SET DataRealizacao = ?, CadernoCampoID = ?, CulturaID = ?, ParcelaID = ? WHERE OperacaoID = ?;
UPDATE Parcela SET Designacao = ?, Area = ?, IntalacaoAgricolaID = ? WHERE ParcelaID = ?;
UPDATE PlanoAgricola SET Ano = ?, "Instalação AgricolaIntalacaoAgricolaID" = ? WHERE PlanoAgricolaID = ?;
UPDATE PlanoColheita SET DataPrevista = ?, QuantidadePrevista = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoColheita = ?;
UPDATE PlanoFertilizacao SET DataPrevista = ?, ViaAplicacaoID = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoFertilizacaoID = ?;
UPDATE PlanoFertilizacao_FatorProdução SET Quantidade = ? WHERE PlanoFertilizacaoID = ? AND FatorProducaoID = ?;
UPDATE PlanoRega SET PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ? WHERE PlanoRegaID = ?;
UPDATE Plantacao SET Quantidade = ? WHERE OperacaoID = ?;
UPDATE Produto SET DesignacaoProduto = ? WHERE ProdutoID = ?;
UPDATE Rega SET Quantidade = ?, Hora = ? WHERE OperacaoID = ?;
UPDATE Sementeira SET Quantidade = ? WHERE OperacaoID = ?;
UPDATE Sensor SET CulturaID = ?, ParcelaID = ? WHERE EstacaoMeteorologicaID = ? AND TipoSensorID = ?;
UPDATE "Tipo Edificio" SET DesignacaoTipoEdificio = ? WHERE TipoEdificioID = ?;
UPDATE TipoCultura SET DesignacaoTipoCultura = ? WHERE TipoCulturaID = ?;
UPDATE TipoFatorProducao SET DescricaoTipoFatorProducao = ? WHERE TipoFatorProducaoID = ?;
UPDATE TipoSensor SET TipoSensor = ?, GrandezaID = ? WHERE TipoSensorID = ?;
UPDATE ViaAplicacao SET DesignacaoViaAplicacao = ? WHERE ViaAplicacaoID = ?;

