UPDATE Cultivo SET CulturaID = ?, ParcelaID = ?, DataInicio = ?, DataFim = ?, Quantidade = ?, UnidadeID = ? WHERE CultivoID = ?;
UPDATE Cultura SET Variedade = ?, EspecieVegetalID = ?, EpocaSementeiraPlantacao = ?, EpocaPoda = ?, EpocaFloracao = ?, EpocaColheita = ? WHERE CulturaID = ?;
UPDATE Edificio SET DesignacaoEdificio = ?, Area = ?, UnidadeID = ?, TipoEdificioID = ? WHERE EdificioID = ?;
UPDATE Elemento SET Nome = ? WHERE ElementoID = ?;
UPDATE EspecieVegetal SET DesignacaoEspecie = ?, NomeComum = ?, TipoCulturaID = ? WHERE EspecieVegetalID = ?;
UPDATE EstaçãoMeteorologica SET  WHERE EstacaoMeteorologicaID = ?;
UPDATE Fabricante SET DesignacaoFabricante = ? WHERE FabricanteID = ?;
UPDATE FatorProducao SET NomeComercial = ?, FabricanteID = ?, FormatoID = ?, TipoFatorProducaoID = ? WHERE FatorProducaoID = ?;
UPDATE FatorProducao_Elemento SET Quantidade = ?, UnidadeID = ? WHERE ElementoID = ? AND FatorProducaoID = ?;
UPDATE Formato SET DescricaoFormato = ? WHERE FormatoID = ?;
UPDATE Grandeza SET DesignacaoGrandeza = ? WHERE GrandezaID = ?;
UPDATE Medição SET ValorMedido = ?, EstacaoMeteorologicaID = ?, TipoSensorID = ? WHERE MedicaoID = ?;
UPDATE Operacao SET ParcelaID = ?, CulturaID = ?, TipoOperacaoID = ?, DataRealizacao = ?, Quantidade = ?, UnidadeID = ?, FatorProducaoID = ? WHERE OperacaoID = ?;
UPDATE Operacao_Produto SET Quantidade = ?, UnidadeID = ? WHERE OperacaoID = ? AND ProdutoProdutoID = ?;
UPDATE Parcela SET Designacao = ?, Area = ?, UnidadeID = ? WHERE ParcelaID = ?;
UPDATE PlanoAgricola SET Ano = ? WHERE PlanoAgricolaID = ?;
UPDATE PlanoColheita SET DataPrevista = ?, QuantidadePrevista = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ?, CultivoCultivoID = ? WHERE PlanoColheita = ?;
UPDATE PlanoFertilizacao SET DataPrevista = ?, ViaAplicacaoID = ?, PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ?, CultivoCultivoID = ? WHERE PlanoFertilizacaoID = ?;
UPDATE PlanoRega SET PlanoAgricolaID = ?, CulturaID = ?, ParcelaID = ?, CultivoCultivoID = ? WHERE PlanoRegaID = ?;
UPDATE Produto SET DesignacaoProduto = ? WHERE ProdutoID = ?;
UPDATE Sensor SET CulturaID = ?, ParcelaID = ?, CultivoCultivoID = ? WHERE EstacaoMeteorologicaID = ? AND TipoSensorID = ?;
UPDATE TipoCultura SET DesignacaoTipoCultura = ? WHERE TipoCulturaID = ?;
UPDATE TipoEdificio SET DesignacaoTipoEdificio = ? WHERE TipoEdificioID = ?;
UPDATE TipoFatorProducao SET DescricaoTipoFatorProducao = ? WHERE TipoFatorProducaoID = ?;
UPDATE TipoOperacao SET DesignacaoTipoOperacao = ? WHERE TipoOperacaoID = ?;
UPDATE TipoSensor SET TipoSensor = ?, GrandezaID = ? WHERE TipoSensorID = ?;
UPDATE Unidade SET DescricaoUnidade = ? WHERE UnidadeID = ?;
UPDATE ViaAplicacao SET DesignacaoViaAplicacao = ? WHERE ViaAplicacaoID = ?;
UPDATE ViaAplicacao_FatorProducao SET  WHERE ViaAplicacaoID = ? AND FatorProducaoID = ?;

